baseurl = "https://lessthanhero.io/"
languageCode = "en-us"
title = "A Series of Semi-empirical Schenanigans"
#copyright = "All rights reserved - Andrew Hamilton - 2020"
#DisqusShortname = "lessthanhero"
theme = "ananke"

Paginate = 7

[params]
  cover = "images/engine.jpg"
  #description = "this is my description"
  #cover = "images/cover.jpg"
  author = "Andrew Hamilton"
  authorlocation = "Los Angeles, CA, USA"
  authorwebsite = "http://lessthanhero.io"
  #bio= "my bio"
  #logo = "images/logo.png"
  #googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = "http://feeds.feedburner.com/..." 
  githubName = "ahamilton55"
  twitterName = "ahamilton55"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  #hideHUGOSupport = false
  mainSections = ["post"]
  background_color_class = "bg-black"
  featured_image = "images/engine.jpg"
  recent_posts_number = 4

[Permalinks]
    post = "/:filename/"